apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: GITEA_REPO_URL
    targetRevision: main
    path: .
    directory:
      include: 'k8s_deployment_service.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
